const cyclePhrases = {
  es: {
    1: [
      'Independencia',
      'Individuación',
      'Iniciaciones',
      'Dejando atrás al niño modelo, para saber ¿Quién soy?.',
      'Creando a un nuevo "YO" más independiente y seguro.',
      'Autoafirmando mi liderazgo e individualidad en el mundo.',
      'Liberaciones y búsqueda de mi propio emprendimiento.',
    ],
    11: [
      'Realización y notoriedad',
      'Inspiración y espiritualidad',
      'Nueva visión de vida',
      'Obligado a madurar y asumir la responsabilidad de mi vida.',
      'Aprendiendo a construir una mejor versión de mi mismo.',
      'Salgo de mis fronteras, cambiando mi mentalidad y visión de vida. ',
      'Apertura de consciencia y conexión con algo más elevado.',
    ],
    3: [
      'Oportunidades',
      'Diversificación',
      'Elecciones',
      'Enamorándome de mi vida y apresurándome a experimentar.',
      'Saliendo de todo lo que me somete, para aprender a elegir ¿Qué quiero?',
      'Expreso mis deseos, sin importar el que dirán. Aprendo a decir "NO".',
      'Me Aperturo a pararme sobre el escenario y tomar el micrófono.',
    ],
    4: [
      'Reorden',
      'Estructuras',
      'Limitaciones',
      'Saliendo de estructuras rígidas, opresivas o desordenadas en la vida.',
      'Reordenando mi vida y construyendo una nueva estructura',
      'Confronto mis limitaciones, me activo y derrumbo los muros que me contienen.',
      'Construyo un nuevo orden en mi vida, con estructuras mas sanas y equilibradas.',
    ],
    5: [
      'Cambios y movimientos',
      'Liberaciones y expansión',
      'Crisis',
      'Me aventuro a ir tras mi pasión y luchar por lo que quiero.',
      'Cambios sorpresivos que me mueven a una nueva realidad.',
      'Necesidad de sentirme vivo e ir en busca de una nueva pasión.',
      'Redireccionando hacia una realidad más libre y auténtica.',
    ],
    6: [
      'Familia',
      'Fertilidad y productividad',
      'Amor propio',
      'Aprendo a construir relaciones emocionales, solidarias, profundas y productivas.',
      'Conecto con mi amor propio y me permito poner mi semilla en el mundo. Soy fértil.',
      'Aprendo a atender mis necesidades,  antes que las de los demás. Me valoro.',
      'Momento de crear y conectar con mi tribu, permitiéndome nutrirlos y ser nutrido.',
    ],
    7: [
      'Responsabilidades',
      'Aprendizajes',
      'Formalizaciones',
      'Asumo responsabilidades y compromisos de vida.',
      'Me perfecciono, aprendo y/o enseño profundizando mi sabiduría.',
      'Me especializo y comprometo en elevar y trasmitir mi conocimiento.',
      'Suelto responsabilidades para comprometerme con mi proyecto de vida.',
    ],
    8: [
      'Potencial constructivo',
      'Empoderamiento',
      'Obstáculos y oposiciones',
      'Desarrollo autoridad y liderazgo en base a mi disciplina, enfoque y determinación. ',
      'Salgo del control, domino y opresión de una autoridad y tomo el liderazgo de mi vida.',
      'Me empodero y construyo mi propio esenario de abundancia y seguridad.',
      'Materializo mi potencial y talento, construyendo un proyecto propio más ambicioso.',
    ],
    9: [
      'Termino de caminos',
      'Reencuentros y reconciliaciones',
      'Fama',
      'Fin de un camino. Crecimiento obligado, sales al mundo por ti mismo.',
      'Asumo mi madurez para ir en busca de autonomía e independencia del clan.',
      'Me identifico con un ideal más grande que "YO". Reconocimiento y notoriedad por lo que hago.',
      'Conecto con mi lado humanista, en busca de una vida con sentido y propósito.',
    ],
  },
};

export default cyclePhrases;
